{
 "title": "Storage Attached Index",
 "description": "Single pane of glass for most important Storage Attached Index (SAI) metrics",
 "tags": [ "os" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(collectd_collectd_queue_length{}, cluster)"
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(dse_table_read_latency_total{cluster=~\"$cluster\", dc=~\"$dc\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(dse_table_read_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", keyspace=~\"$keyspace\"}, table)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}, instance)"
   },
   {
    "name": "latency",
    "label": "Percentile",
    "query": "0.999,0.99,0.98,0.95,0.90,0.75,0.50"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "description": "Nodes that are currently running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"} >= 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "description": "Nodes that are currently not running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(absent(sum(rate(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[5m])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "singlestat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "CQL Requests / $rate",
   "type": "singlestat",
   "description": "Rate of CQL requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "singlestat",
   "description": "Rate of Dropped requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_table_dropped_mutations_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "content": "<a href=\"https://cassandra.apache.org\" target=\"new\"><img src=\"https://cassandra.apache.org/img/cassandra_logo.png\"/></a>"
  },
  {
   "title": "CQL Clients",
   "type": "singlestat",
   "description": "Number of connected clients during this time window",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Timeouts / $rate",
   "type": "singlestat",
   "description": "Client timeouts over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_timeouts_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Hints / $rate",
   "type": "singlestat",
   "description": "Hints stored over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_storage_hints_on_disk_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "singlestat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_table_live_disk_space_used_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC Time / $rate",
   "type": "singlestat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(dse_jvm_gc_time{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  { "title": "Cluster Index Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Index Count",
   "type": "graph",
   "description": "Global count of Storage Atttached Indexes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_index_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Index Count",
   "type": "graph",
   "description": "Global count of Storage Atttached Indexes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_index_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Index Building Count",
   "type": "graph",
   "description": "Global count of Storage Atttached Indexes that are building",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_index_builds_in_progress{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Index Disk Used Bytes",
   "type": "graph",
   "description": "Global view of SAI disk used in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_disk_used_bytes{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Index Queryable Count",
   "type": "graph",
   "description": "Global count of Storage Atttached Indexes that are queryable",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_queryable_index_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "open_index_files",
   "type": "graph",
   "description": "Global count of Storage Atttached Indexes open_index_files",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_index_group_metrics_open_index_files{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Column Index Builds InProgress",
   "type": "graph",
   "description": "Global view of SAI Column Index Builds In Progress",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_column_index_builds_in_progress{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Disk Percentage Of BaseTable",
   "type": "graph",
   "description": "SAI size on Disk as a percentage of table size per table.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_disk_percentage_of_base_table{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "live_memtable_index_write_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_index_metrics_live_memtable_index_write_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"})",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  { "title": "Table Index Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Index Count",
   "type": "graph",
   "description": "Table-level count of Storage Atttached Indexes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_index_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  },
  {
   "title": "Index Queryable Count",
   "type": "graph",
   "description": "Table-level count of Storage Atttached Indexes that are queryable",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_queryable_index_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  },
  {
   "title": "Index Building Count",
   "type": "graph",
   "description": "Table-level count of Storage Atttached Indexes that are building",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_total_index_builds_in_progress{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  },
  {
   "title": "Index Disk Used Bytes",
   "type": "graph",
   "description": "Table-level view of SAI disk used in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_disk_used_bytes{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  },
  {
   "title": "Index Disk Usage Percentage of Base Table",
   "type": "graph",
   "description": "Table-level view of SAI disk usage as percentage of base table size",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_table_state_metrics_disk_percentage_of_base_table{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  },
  {
   "title": "Index Memtable Bytes",
   "type": "graph",
   "description": "Table-level view of SAI memtable bytes used",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_attached_index_index_metrics_memtable_index_bytes{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\", table=~\"$table\"}) by (table, $by)",
     "legendFormat": "{{$by}} : {{table}}"
    }
   ]
  }
 ]
}